### ISSUE TITLE
Modules version error after build

### ISSUE THREAD

**Issue by Nemolo** [victordzmr/nginx-compiler#1]
After building the new nginx, i get this error,
`/usr/lib64/nginx/modules/ngx_http_geoip_module.so" version 1010002 instead of 1012000 in /usr/share/nginx/modules/mod-http-geoip.conf:1`

should i disable or upgrade manually all the pre-existing modules?

**Comment by victordzmr** [comment]
It seems that you are trying to load the GeoIP module dynamically. To do this, you must add the option `--with-http_geoip_module=dynamic` to the `compile.sh` file. For example, paste it after the line 81 and add a backslash  (`\`) at the end.

You can also load the GeoIP module statically. In this case you'll have to add the `--with-http_geoip_module` option and remove the corresponding `load_module` instruction from your Nginx configuration (find something like `load_module "modules/ngx_http_geoip_module.so";`).

You can find more info about dynamic modules [here](https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/).

I hope this solves your problem!

**Comment by Nemolo** [comment]
i managed to get it going, thanks
